services:
  db:
    image: postgres:15
    environment:
      - POSTGRES_USER=kitsune
      - POSTGRES_PASSWORD=kitsune
      - POSTGRES_DB=kitsune
    volumes:
      - dbdata:/var/lib/postgresql/data
  redis:
    image: redis:7
    volumes:
      - redisdata:/data
  kitsune:
    build: .
    environment:
      DATABASE_URL: postgres://kitsune:kitsune@db/kitsune
      JOB_QUEUE_REDIS_URL: redis://redis
      URL_SCHEME: http
      URL_DOMAIN: localhost:5000
      # SERVER_OIDC_SERVER_URL: https://weird.one/auth/v1
      # SERVER_OIDC_CLIENT_ID: https://git.weird.one/zicklag/localhost-oidc-config/raw/branch/main/kitsune.json
      # SERVER_OIDC_CLIENT_SECRET: unused
    ports:
      - 5000:5000

volumes:
  dbdata:
  redisdata:
