services:
  db:
    image: postgres:15
    environment:
      - POSTGRES_USER=kitsune
      - POSTGRES_PASSWORD=kitsune
      - POSTGRES_DB=kitsune
    volumes:
      - dbdata:/var/lib/postgresql/data
  redis:
    image: redis:7
    volumes:
      - redisdata:/data
  kitsune:
    build: .
    environment:
      DATABASE_URL: postgres://kitsune:kitsune@db/kitsune
      JOB_QUEUE_REDIS_URL: redis://redis
      URL_SCHEME: http
      URL_DOMAIN: localhost:3000
    ports:
      - 5000:5000

volumes:
  dbdata:
  redisdata:
